### ISSUE TITLE
Move Reporters used for logging in tools into a shared project

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Common#105]
We're in the process of removing Microsoft.DotNet.Cli.Utils from our tools. One of the side effects was that we had to copy in some code which allows for printing output with color to the console. For RC2, we'll copy the code in to individual repos. For RTM, we should commonize this code.

**Comment by NTaylorMullen** [comment]
The cli.utils package no longer depends on app insights and ef, scaffolding and razor already use the package for more than just the Reporter. Talked with @Eilon and decided that this issue no longer makes sense. Also, for consistency just using the cli.utils package now would be consistent across all of our tools.
