### ISSUE TITLE
Should default(StringSegment) != default(StringSegment)?

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Common#111]
I've noticed that `default(StringSegment) == default(StringSegment)` evaluates to `false`, [which seems to be done for a reason in the source code](https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.Primitives/StringSegment.cs#L132), but I'm not sure what that reason is. I was just wondering if someone could fill me in, I'm just curious.

**Comment by pranavkm** [comment]
Seems like an oversight. cc @javiercn

**Comment by Eilon** [comment]
Yup this just seems like a bug.

**Comment by javiercn** [comment]
Yep, @rynowak is there any perf reason to not do string.Compare directly? I've done a quick test of the API on the interactive window in VS and it works fine for null values. (We will want a theory test here, though)

**Comment by Eilon** [comment]
@jbagga please enjoy this bug 😄

**Comment by Eilon** [comment]
cc @pranavkm for FYI information.
