### ISSUE TITLE
Unable to resolve 'Microsoft.AspNetCore.Cors (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Common#117]
Unable to resolve 'Microsoft.AspNetCore.Cors (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.

**Comment by BrennanConroy** [comment]
Please stop opening all these issues. You need to try to restore again in a few minutes, you hit our myget feed when it was being pushed to, it happens every now and then

**Comment by xatabhk** [comment]
It happened when I run “dotnet restore”

**Comment by BrennanConroy** [comment]
Yes, and I said you need to run it again in a few minutes

**Comment by xatabhk** [comment]
Got it.

**Comment by BrennanConroy** [comment]
Next time you have an issue from multiple repos it is best if you put the errors all in one issue, and if you don't know where it belongs put it in the home repo.
