### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment'

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Common#120]
In RC1, i'm using the following link action to display the corresponding source file content.

`<a href="/Employee?file=Views\Accounts\default.cshtml" class="e-link">Default</a>`
`<a href="/Employee?file=Views\Accounts\Banking.cshtml" class="e-link">Accounts</a>`

In recent RC2 update, when i'm click the same link will throws the error like as below 

![error](https://cloud.githubusercontent.com/assets/5366630/15756456/f6151974-291e-11e6-8b62-0faf5bc1fc20.PNG)

If there is any steps i need to resolve this one?

Greetings... 
Manikandan

**Comment by pranavkm** [comment]
See this annoucement: https://github.com/aspnet/Announcements/issues/171. We stopped injecting `IApplicationEnvironment` in RC2. You can use `PlatformServices.Default.ApplicationEnvironment` to get to it. That said, if you're trying to get to the app root, consider using `IHostingEnvironment.ContentRoot`.

**Comment by manikandan05** [comment]
Hi @pranavkm.  Thanks you so much. Now its working fine, also got relief from two days headache. :smile:
