### ISSUE TITLE
Why script and CSS files appended into body tag instead Head tag? Also append one unnecessary string value in body tag in RC2

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Common#121]
Hi,, This is general query. When i'm deploying a simple RC2 application i have noticed all scripts and CSS files appended within the body tag. And one more the extra string will be added in the starting body tag. The head tag will be empty.

**This is an issue?** 

![errors](https://cloud.githubusercontent.com/assets/5366630/15758265/66fb5768-2927-11e6-9360-029e0fa2d0f4.PNG)

Greetings.
Manikandan

**Comment by moozzyk** [comment]
Looks like this: https://github.com/aspnet/IISIntegration/issues/199

**Comment by Tratcher** [comment]
Or aspnet/Mvc#4671. Have you tried commenting out BrowserLink in your Startup?

**Comment by manikandan05** [comment]
Hi @Tratcher , i comment BrowserLink() in startup.cs. This will be working fine what i have expected. But i need one confirmation, removing this line may cause any issue in further? or may be any fixes related to BrowserLink() in future releases?

Greetings..
Manikandan

**Comment by Tratcher** [comment]
BrowserLink is getting fixed. In the meantime your app should be fine without it, it's just a debugger tool.

**Comment by manikandan05** [comment]
ok @Tratcher , Thanks for your valuable suggestion :smile: 

i will close now.

Greetings..
Manikandan
