### ISSUE TITLE
Remove RuntimeEnvironment.Sources when RuntimeInformation has necessary features

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Common#130]
From https://github.com/aspnet/PlatformAbstractions/issues/34

**Comment by BrennanConroy** [comment]
Depends on https://github.com/dotnet/corefx/issues/4741 and https://github.com/dotnet/corefx/issues/8920

**Comment by Eilon** [comment]
@BrennanConroy the two linked bugs are closed. Do we still need to take any action on this bug?

**Comment by Eilon** [comment]
Work needs to be done in 2.0.0.

**Comment by BrennanConroy** [comment]
The APIs we need are in `netstandard1.7`. We will revisit this later in the milestone

**Comment by davidfowl** [comment]
@BrennanConroy which ones

**Comment by BrennanConroy** [comment]
Environment.OSVersion, and we'll have to look at the places that use RuntimeEnvironment.RuntimeType and change them to use Environment.FrameworkDescription

**Comment by davidfowl** [comment]
Where do we use `RuntimeEnvironment.Sources` today?

**Comment by BrennanConroy** [comment]
https://github.com/search?q=org%3Aaspnet+runtimeenvironment&type=Code

WebListener, Testing, Hosting,

**Comment by Eilon** [comment]
Moving to 2.0.0-preview2.

**Comment by BrennanConroy** [comment]
Done
