### ISSUE TITLE
StringSegment GetHashCode() includes the Offset but Equals doesn't care about it

### ISSUE THREAD

**Issue by IanMercer** [aspnet/Common#137]
Surely `GetHashCode()` should not rely on the `Offset` since in `Equals`, two `StringSegments` are equal if they have equal values regardless as to where they are located in the string.

**Comment by pranavkm** [comment]
Yup, seems like a bug. It should probably add individual chars to the `HashCodeCombiner` to compute the hash.

**Comment by IanMercer** [comment]
I think if you just delete these two lines from `GetHashCode` it's all good:

            hash.Add(Offset);
            hash.Add(Length);

But yes, if you can do it without an allocation that might be better.

**Comment by pranavkm** [comment]
Wouldn't that still be problematic if the two strings are different but the `StringSegments` are identical.

**Comment by IanMercer** [comment]
`Value` is `Buffer.Substring(Offset, Length)`

So either you add `Value` to the Hashcode (which is effectively what Equals is looking at), or you add the characters from `Buffer` from position `Offset` for `Length` characters.

**Comment by pranavkm** [comment]
Huh. I thought it was adding the `Buffer` to the combiner. Allocating as part of `GetHashCode` seems counter to the purpose of this type. cc @rynowak.

**Comment by IanMercer** [comment]
Interestingly [`ArraySegment`](http://referencesource.microsoft.com/#mscorlib/system/arraysegment.cs) has different (and arguably rather useless) semantics for `Equals`: it does a compare on the whole buffer and the length and the offset. When would that ever be useful? Since `StringSegment` and `ArraySegment` are convenient ways of slicing strings and arrays to save copying you'd expect `Equals` to work like it would if you had copied the segment out, i.e. do the characters match (or do the array elements match).

**Comment by Eilon** [comment]
@pranavkm please confirm with @rynowak what the expectation is here.
