### ISSUE TITLE
Introduce a time-constant comparer for crypto purposes

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Common#140]
Both [DataProtection](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.Cryptography.Internal/CryptoUtil.cs#L75-L102) and [Identity](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/PasswordHasher.cs#L67-L85) have their time-constant comparison helper but none of them is public. It would be nice to refactor that and have a common implementation in a shared sources package that could also be used by third-party packages.

Note: as mentioned by @blowdart, CoreFX will likely get such a method in the future (1.2 or 2.0?), but I suppose it will require a newer .NET Standard contract (1.7/1.8?) or .NET Desktop TFM (4.6.3), which will make it incompatible with packages that need to target .NET 4.5.1 or older .NET Standard TFMs.

**Comment by blowdart** [comment]
CoreFX is picking this up and putting it where it should belong

https://github.com/dotnet/corefx/issues/10749

**Comment by PinpointTownes** [comment]
@blowdart you know, in the real world, not everyone can afford targeting the most recent TFMs (which is something I deeply regret). What's the option you'd recommend for older TFM? Rolling your own comparer?

**Comment by blowdart** [comment]
I'd still say this isn't an ASP.NET concern, but a CoreFX one.

**Comment by PinpointTownes** [comment]
That's precisely why I opened this ticket in the Common repo :smile:

**Comment by blowdart** [comment]
Which is still an asp.net repo. Not corefx. If you want it then argue for it to arrive quicker in the CoreFX issue I linked to.

**Comment by davidfowl** [comment]
Common is mostly for things shared internally within the ASP.NET repositories. 

> What's the option you'd recommend for older TFM? Rolling your own comparer?

Request that on the CoreFx issue. They can move it to another namespace so it can exist in a lower netstandard version.

**Comment by PinpointTownes** [comment]
@davidfowl done, thanks.

> Which is still an asp.net repo. Not corefx.

Yeah. Just like Configuration, DependencyInjection, Logging or EntityFramework, tho' none of them is directly to ASP.NET :trollface:
