### ISSUE TITLE
Please, give some examples of CommandLineUtils usage

### ISSUE THREAD

**Issue by quicktrick** [aspnet/Common#141]
Thanks in advance!

**Comment by moozzyk** [comment]
https://github.com/aspnet/IISIntegration/blob/ef6533cf8524937203847cedf9701fec11740161/src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Program.cs#L14

**Comment by Eilon** [comment]
Indeed, the best place to find sample usage is in other projects that use this library. It's not really a part of ASP.NET/EF per se, it's just an implementation detail of various command line utilities that needed this functionality. We hope others will find it useful, but we have no plans to write any specific samples or docs for it.

**Comment by nareshpatel** [comment]
I found another example of CommandLineUtils nugetpackage in [aspnet benchmarks](https://github.com/aspnet/benchmarks/blob/dev/src/BenchmarksClient/Startup.cs#L39) repository.

**Comment by necoras** [comment]
There's an example and some explanation [here](https://msdn.microsoft.com/en-us/magazine/mt763239.aspx), though I'm still trying to make sense of it myself.

**Comment by llint** [comment]
https://gist.github.com/llint/a361312e9ae01613b0f3ddfc39b3ccf2

**Comment by MaxCheetham** [comment]
Here is a more OOP baised usage:
https://github.com/MaxCheetham/CommandLineUtilsUsage

let me know if you have any questions.

**Comment by Eilon** [comment]
@MaxCheetham this is barely a supported library, so per my earlier comment it's generally "just enough" for what the ASP.NET and EF Core command-line tools need to operate. I'm glad that others have found it useful, but we're not looking to add anything to it if it's outside the scope of what is needed here.

**Comment by MaxCheetham** [comment]
@Eilon Understood. As an aside it has been really helpful for a number of my projects so thanks for your work!

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2369
