### ISSUE TITLE
[AwaitableStream] Serialize producer and consumer

### ISSUE THREAD

**Issue by anurse** [aspnet/Common#149]
Since we are trying to avoid buffering in `AwaitableStream`, we need to fully serialize the producer and the consumer. Right now, this is done by waiting until the `ReadAsync` continuation is called before returning from `WriteAsync`. However, if the `ReadAsync` continuation `await`s something else, it will return while the buffer is still in use. If the user hasn't marked the buffer as unconsumed by explicitly calling `Consumed(0)`, we'll mark the entire buffer as consumed even when the caller may still be using it, which would allow the writer (i.e. Kestrel) to clobber it.

Instead, we should move that consumption to the beginning of `WriteAsync` and have `WriteAsync` **wait** until a matching `ReadAsync` arrives before the auto-consumption logic fires and we accept the next buffer.

**Comment by halter73** [comment]
Is that latest commit PR-worthy?

**Comment by halter73** [comment]
Nvm, Just saw #150.

**Comment by anurse** [comment]
We removed AwaitableStream.
