### ISSUE TITLE
Stop using `Unsafe.CopyBlock` in InplaceStringBuilder.Append

### ISSUE THREAD

**Issue by pakrym** [aspnet/Common#158]
It works but by specification requires writes to be aligned. If/when corefx would add `Unsafe.CopyBlockUnaligned` we should start using it.

https://github.com/dotnet/corefx/issues/12243

**Comment by Eilon** [comment]
Do we know the alternative API?

**Comment by Eilon** [comment]
(That we can use today.)

**Comment by benaadams** [comment]
Its been added https://github.com/dotnet/corefx/pull/12443 don't know when it would be in nuget or aspnet-ci though?

**Comment by benaadams** [comment]
Could use `Buffer.MemoryCopy` but is only Core and 4.6+

**Comment by davidfowl** [comment]
The API exists now. We can do this work.

**Comment by Eilon** [comment]
@pakrym feel free to do for RTM.

**Comment by benaadams** [comment]
Has it been released on nuget yet though?

**Comment by Eilon** [comment]
@benaadams as long as it's in the daily builds that we use then it's good.

**Comment by pakrym** [comment]
@Eilon @davidfowl from what @pranavkm told me version 4.3 of the package is shipping. And new API's are in 4.4

**Comment by Eilon** [comment]
Oh, so does this need to wait for 1.2.0 then?

**Comment by pakrym** [comment]
@Eilon yes.

**Comment by Eilon** [comment]
Okie dokie.

**Comment by pranavkm** [comment]
Should be unblocked now - https://github.com/aspnet/Common/commit/0f0c9380a4746d0d76e9995d23af582c19499647

**Comment by Eilon** [comment]
Moving to 2.0.0-preview2.
