### ISSUE TITLE
StringSegment bounds checking calculation can overflow

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Common#172]
The calculation here https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.Primitives/StringSegment.cs#L50 can overflow to a negative value if both offset and length are big enough.

**Comment by pranavkm** [comment]
Do you want to do a quick scan across repos and see if this crops up elsewhere? I see a at least one place in Mvc which has the same issue:

* https://github.com/aspnet/Mvc/blob/0eea3c2651ac3999d790b91d3fb43d840944f4ec/src/Microsoft.AspNetCore.Mvc.Core/Formatters/MediaType.cs#L57
