### ISSUE TITLE
Investigate using ConcurrentBag for DefaultObject pool (post corefx merge) 

### ISSUE THREAD

**Issue by benaadams** [aspnet/Common#174]
When this is merged to corefx dotnet/corefx#14126 it will be worth (re)visiting ConcurrentBag for object pooling.

/cc @rynowak @davidfowl

**Comment by rynowak** [comment]
Is there some data to go with this? or just a feeeeeeeeeeeeeeeeeeeeeeeeeeeling?

**Comment by benaadams** [comment]
Had data to show why you shouldn't use ConcurrentBag or ConcurrentStack but ConcurrentQueue, which is why Kestrel uses the Queue for its pool.

Corefx change invalidates this data - so needs revisiting; don't have data yet...

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2368
