### ISSUE TITLE
Reduced TFM needed for Microsoft.Extensions.CommandLineUtils from net451 to net45

### ISSUE THREAD

**Issue by rrelyea** [aspnet/Common#178]
Similar to our request https://github.com/aspnet/FileSystem/issues/212, could you please reduce the TargetFramework for this package to net45, from net451 if possible.

https://github.com/aspnet/Common/blob/a854741b610134703627a49b5872bcf215e8303b/src/Microsoft.Extensions.CommandLineUtils/project.json 

Customers feel pain as we have to move NuGet.exe to require newer .net versions installed on build servers.

/cc @emgarten @zhili1208

**Comment by davidfowl** [comment]
.net 4.5 isn't even supported....

**Comment by rrelyea** [comment]
We had the exact same discussion last time.
If this is an easy change, it would be ideal.

**Comment by Eilon** [comment]
At this point I think we'll be moving this to netstandard2.0 only anyway... so I don't see us adding this...
