### ISSUE TITLE
Pkg rename: .Internal -> .Sources

### ISSUE THREAD

**Issue by muratg** [aspnet/Common#18]
Change .Internal for the packages below to .Sources, and update the references to these packages elsewhere.

- Microsoft.Framework.BufferEntryCollection.Internal
- Microsoft.Framework.CopyOnWriteDictionary.Internal
- Microsoft.Framework.NotNullAttribute.Internal
- Microsoft.Framework.PropertyActivator.Internal
- Microsoft.Framework.PropertyHelper.Internal
- Microsoft.Framework.TypeNameHelper.Internal

**Comment by troydai** [comment]
Done 2b845287bc7249913bb07f3f4920fb16405ae68c
