### ISSUE TITLE
CommandLineUtils: support aliases

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Common#188]
Would be nice to create shorter versions of subcommands.

```
app.Command("long-sub-command-name").Alias("lscn")
```

Help:
```
Usage:

Commands:
    long-sub-command-name       Description
                                Aliases: lscn
```

**Comment by Eilon** [comment]
Let's come up with the list of command names we have, what we'd want to shorten them to, and circulate w/ the command owners + engr team.

**Comment by natemcmaster** [comment]
There wasn't enough interested in this. Closing as wontfix.
