### ISSUE TITLE
CommandLineUtils: Match options using case-insensitive comparison

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Common#194]
Currently, CommandLineUtils uses a case-insensitive comparison when matching commands:

https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.CommandLineUtils.Sources/CommandLine/CommandLineApplication.cs#L367

But case-sensitive comparison when matching options:

https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.CommandLineUtils.Sources/CommandLine/CommandLineApplication.cs#L152

I think these should both use case-insensitive.

**Comment by Brar** [comment]
I kind of disagree.
While case-insensitivity is common for long options it is a stopper for short options.
I know of quite a few applications out there where "-v" stands for "--verbose" while "-V" stands for "--version".
So my suggestion would be the following:
Support case-insensitivity independently for short options and long options and make it default for long options.

**Comment by natemcmaster** [comment]
I agree @Brar's point. Also, this a potentially a breaking change for apps on 1.x. I suggest we make case insensitive comparison an option, but not the default.

**Comment by mikeharder** [comment]
Agree with short options, but I would make case-insensitive the default for long options.  Breaking changes are OK in 2.0.

**Comment by Eilon** [comment]
We have a few command line things I think we need to discuss for triage... I'll send an email on this (incl. you @mikeharder and @natemcmaster ).

**Comment by Brar** [comment]
When discussing command line things, please consider that compatibility of command line interfaces has a pretty high value in the Unix world. Some applications are written as drop in replacements for other (older) ones but maintain the same options and arguments. (cc -> gcc; lex -> flex, yacc ->bison, ...).
While it would always be possible to wrap new applications with a batch or a shell script, a high level of flexibility in the CommandLineUtils would be helpful for writing command line compatible replacement-applications.

**Comment by Brar** [comment]
Some things that might be useful:
http://perldoc.perl.org/Getopt/Long.html#Command-Line-Options%2c-an-Introduction
http://perldoc.perl.org/Getopt/Long.html#Case-and-abbreviations

**Comment by Eilon** [comment]
Discussed in triage; there is no pressing need to change this, so closing it.

**Comment by brobichaud** [comment]
What a ridiculous argument. Clearly there are both sides to this coin, so why not make it a developer option? I can't believe this was dismissed so rapidly.

**Comment by Eilon** [comment]
@brobichaud adding features has cost, and we felt that it wasn't worth the cost, given that this library has limited usage. One of the engineers on the team forked the project at https://github.com/natemcmaster/CommandLineUtils and has added various features, so perhaps this option is available there.

**Comment by Eilon** [comment]
@brobichaud unfortunately cost is quite often the main reason. We'd love to add lots of features to lots of areas but we have to prioritize our efforts. Even features/fixes contributed by community members have a non-zero cost (the code has to be reviewed, maintained, etc.).

In this specific case the original issue was an "internal find" (as in, not customer complaint), and it remained a fairly quiet issue for over a year.

**Comment by Brar** [comment]
> it remained a fairly quiet issue for over a year

I think that this is rather because you've internalized the whole api than because of lack of interest.

I'm glad @natemcmaster forked the project and maintains a public command line argument api that Microsoft can only maintain internally (separately in several different projects with slight modifications)

**Comment by natemcmaster** [comment]
FYI:  the API you're looking for is  [McMaster.Extensions.CommandLineUtils.CommandLineApplication.OptionsComparison](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=OptionsComparison#McMaster_Extensions_CommandLineUtils_CommandLineApplication_OptionsComparison)
