### ISSUE TITLE
Invalid embedded resource in Microsoft.Extensions.WebEncoders.Sources

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Common#203]
The resources in the .resx file is not being correctly embedded by the CLI used to build the FTS packages. This is breaking when loading assemblies for UWP (https://github.com/aspnet/HttpAbstractions/issues/785) apps during compile time and for .NET Core and .NET Framework during runtime. The suggested fix is to move the resource into a .cs file like we have done in the dev branch, since it is only one string.

cc @Eilon @anurse

**Comment by pranavkm** [comment]
If we do this, we should also consider removing support for resx files in shared-src packages (https://github.com/aspnet/KoreBuild/blob/dev/build/shared/sharedsources.csproj#L33).

**Comment by JunTaoLuo** [comment]
This is a bug with the project.json based CLI so this only affects FTS. This package doesn't exist in LTS and we build with MSBuild based CLI in 2.0.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
