### ISSUE TITLE
`TypeNameHelper` does not handle most nested classes correctly

### ISSUE THREAD

**Issue by dougbu** [aspnet/Common#21]
With a simple, non-generic nested class such as

``` c#
namespace Namespace
{
  public class OuterClass
  {
    public class InnerClass
    {
    }
  }
}
```

`TypeNameHelper.GetTypeDisplayName(typeof(InnerClass))` returns "Namespace.OuterClass+InnerClass" instead of "Namespace.OuterClass.InnerClass".  This is not useful when generating C# code.

Note `TypeNameHelper` does the correct thing (special-cases the `+`) for nested generic classes.  In other words, it handles the more complex case and not the simple one.

**Comment by Eilon** [comment]
`TypeNameHelper` is not for generating code. It's for generating pretty-print versions of types, e.g. for use in logging.

**Comment by dougbu** [comment]
Interesting.  Then why does it special-case `+` for nested generics?  And what do we have for correctly generating type names in code (Razor hasn't really needed to deal with the general problem)?

**Comment by Eilon** [comment]
It special-cases `+` because that's what the person who wrote the code made it do. That person was me :smile: 

Razor doesn't really use any `Type` to `string` conversion does it? I thought it just takes whatever the user typed in, in the form of a string, no?

**Comment by Eilon** [comment]
Closing because this bug is ancient.

**Comment by NTaylorMullen** [comment]
As a side note, @ajaybhargavb wrote a lot of code like this for ViewComponentTagHelpers. That did cover nested classes.

**Comment by Eilon** [comment]
Yeah, the requirements were very different. In this case we were optimizing for "prettiness" and in the Tag Helpers case we optimized for "C# correctness."
