### ISSUE TITLE
Properly Implement StringSegment and StringSegmentComparer GetHashCode

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Common#232]
https://github.com/aspnet/Common/issues/213
StringSegment.GetHashCode and StringSegmentComparer.GetHashCode(StringSegment) both substring and then string.GetHashCode() which defeats the purpose of using StringSegment.

Note that .NET Core strings use randomized hash codes to mitigate issues like dictionary hash collision attacks.

The header parsers in HttpAbstractions call both of these methods the header value types GetHashCode implementations, but I'm not aware of any instances where those header value types are used as keys into hashed collections.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2365
