### ISSUE TITLE
Base64Url encoding duplicated with HttpAbstraction repository

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Common#237]
https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/Base64UrlTextEncoder.cs

Related #93 

In addition, can we consider to optimize the encoder by avoiding to first convert to Base64 then replace to url-safe character. instead, convert directly to Base64Url, simply by changing the Base64 character map and by removing the padding?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2362
