### ISSUE TITLE
Add overload for StringComparison for StringValues comparisons

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Common#246]
Currently we rely on the default string comparison which uses case-sensitive culture-insensitive compare here https://github.com/aspnet/Common/blob/e68cd05c7cff78de83535504a9c20b8bebb6af2f/src/Microsoft.Extensions.Primitives/StringValues.cs#L268. Following up the discussion on https://github.com/aspnet/IISIntegration/pull/386#discussion_r124330773, we may want to add overloads to specify the StringComparison that should be used.

**Comment by pranavkm** [comment]
Alternatively, something like https://github.com/aspnet/Common/blob/e68cd05c7cff78de83535504a9c20b8bebb6af2f/src/Microsoft.Extensions.Primitives/StringSegmentComparer.cs.

**Comment by Eilon** [comment]
@JunTaoLuo - https://github.com/aspnet/Common/blob/e68cd05c7cff78de83535504a9c20b8bebb6af2f/src/Microsoft.Extensions.Primitives/StringValues.cs#L268 is case-sensitive, culture-sensitive, no? In other words, it's checking for an exact match.

What exactly are we trying to fix here, anyway? (I.e. is something broken? Would we use this anywhere? If so, why?)

**Comment by JunTaoLuo** [comment]
@Eilon There may be cases where we will want to use case-insensitive compare but currently we have no way of doing that with two StringValue types. The only way to do that is to iterate through both StringValues and compare the strings inside. Would be better if we can specify a StringComparison or add a StringComparer.

**Comment by Eilon** [comment]
Closing because there doesn't seem to be a strong need for this.
