### ISSUE TITLE
Microsoft.Extensions.CommandlineUtils: Multiple arguments to different commands fail

### ISSUE THREAD

**Issue by patriksvensson** [aspnet/Common#247]
When trying to run the following program, I get an exception telling me that `bar` is unrecognized. Not sure if I'm doing something wrong or if it's a bug.

```Powershell
C:\Test\> ConsoleApp6.exe foo Hello bar World
```

```csharp
public static void Main(string[] args)
{
    var app = new CommandLineApplication();

    app.Command("foo", foo =>
    {
        var input = foo.Argument("input", "<input>");
        foo.Command("bar", bar =>
        {
            var output = bar.Argument("output", "<output>");
            bar.OnExecute(() =>
            {
                Console.WriteLine($"Input = {input.Value ?? "N/A"}");
                Console.WriteLine($"Output = {output.Value ?? "N/A"}");
                return 0;
            });
        });
    });

    app.Execute(args);
}
```

The exception:

```
Unhandled Exception: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument 'bar'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ConsoleApp6.Program.Main(String[] args) in c:\users\patrik\documents\visual studio 2017\Projects\ConsoleApp6\ConsoleApp6\Program.cs:line 31
```

**Comment by Eilon** [comment]
Moving to backlog because I don't think this affects any ASP.NET/EF Core commands. This library is really meant just for the ASP.NET/EF Core command-line tools, so we do very little work on this if it doesn't affect those scenarios. We'd consider a PR for this if you are able to figure out what's going on.

**Comment by juanfranblanco** [comment]
@Eilon The command line utils project is surely needed in .Net in general. We do seriously lack behind other frameworks. Why don't you move it to another repository where it can be maintained and extended. This was published as the "new" way to work with command line applications in MSDN, and I just find out that you are not doing any new releases.

**Comment by juanfranblanco** [comment]
I don't think https://github.com/aspnet/Common/commit/2230370a3985fd1bbeebbdd904a3dd348f612d35#diff-82723d6f4f27e574c479b7431f7a5249 is the way to go without further communication.

**Comment by Eilon** [comment]
@juanfranblanco - there's a "CoreFX Lab" project called System.CommandLine that should be worth checking out: https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine

**Comment by juanfranblanco** [comment]
@Eilon  thanks!
