### ISSUE TITLE
Continue work Microsoft.Extensions.CommandlineUtils

### ISSUE THREAD

**Issue by juanfranblanco** [aspnet/Common#257]
Microsoft.Extensions.CommandlineUtils is a fantastic and needed library. 

I just found out that there are not going to be more updates and/or releases on the library as it will be used only for Asp.net.

Will it be possible for you to reconsider this, or make it part of another open source project?

Thanks

**Comment by Eilon** [comment]
Hi @juanfranblanco unfortunately as you've found out, we're not planning on adding features to it that are outside the scope of what is needed by ASP.NET Core and EF Core. We have to be careful where we spend our time and resources and unfortunately this just isn't an area we can devote ourselves to (it would come at the expense of other higher priority areas).

I've noted in other issues that there's a "CoreFX Lab" project called System.CommandLine that should be worth checking out: https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine

Or, of course, anyone in the community is more than welcome to create a new project based on this package and we'd even be happy to link to it from here. The sources here are licensed under the very friendly Apache 2.0 license.

So, sorry to give the bad news, but hopefully another person or group can take the lead on this.

**Comment by natemcmaster** [comment]
> Or, of course, anyone in the community is more than welcome to create a new project based on this package and we'd even be happy to link to it from here.

I've decided to take you up on that => #261. And just to be clear, this fork will be maintained by me in an unofficial capacity.
