### ISSUE TITLE
Add 127.0.0.1 and [::1] to the SAN list for the development certificate

### ISSUE THREAD

**Issue by anurse** [aspnet/Common#267]
SAN: [Subject Alternate Name](https://en.wikipedia.org/wiki/Subject_Alternative_Name)

That means it should work even when the user navigates to 127.0.0.1 or [::1].

@javiercn we talked about this with @Tratcher and it seems like this is the place to log it (regardless of where the Kestrel discussions go ;)). Feel free to correct me if I'm wrong

Any concerns @blowdart ? It doesn't seem problematic to me.

**Comment by javiercn** [comment]
I believe chrome won’t think its valid https://stackoverflow.com/questions/43770712/self-signed-certificate-for-127-0-0-1-not-accepted-by-chrome

**Comment by javiercn** [comment]
More data https://stackoverflow.com/questions/24971552/why-ie-rejects-a-self-signed-localhost-certificate-for-127-0-0-1-only-when-chro

**Comment by anurse** [comment]
The second thing you posted indicates IE accepts it if you write it as a DNS entry rather than an IP entry. Do you know if Firefox supports it? It seems like a harmless thing to do if it helps some users out. But if the general consensus is that they don't work, that's OK with me

**Comment by blowdart** [comment]
Windows 8 and below don't support IP addresses in SAN extension. CAB forum says you can only put IP addresses in SAN extension. CAB forum also says don't do this any more, because it's bad. No public CA will issue IP addresses any more, and they've revoked certs containing them.

So no, host names only.

**Comment by anurse** [comment]
:+1:
