### ISSUE TITLE
Add ConsoleReporter

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Common#276]
Add the `ConsoleReporter` as seen in [BuildTools](https://github.com/aspnet/DotNetTools/blob/8c327312824457b4dd1fccd814380894edf36eab/shared/ConsoleReporter.cs) to `Microsoft.Extensions.CommandLineUtils.Sources`.

**Comment by ryanbrandenburg** [comment]
After adding it here, remove any copies that have popped up in repos like Infrastructure.

**Comment by Eilon** [comment]
Go for it 😄

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2360
