### ISSUE TITLE
Remove 'dnxcore50' if the 'dotnet' present in the same project.json

### ISSUE THREAD

**Issue by troydai** [aspnet/Common#29]
With `dotnet` framework presents in the project, `dnxcore50` is really not needed.

**Comment by Eilon** [comment]
What's the issue? Not sure I understand the title.

**Comment by Eilon** [comment]
What's the "sample" project.json?

**Comment by troydai** [comment]
Sorry, my typo. I mean 'same'. (Title just updated)

**Comment by muratg** [comment]
Example: https://github.com/aspnet/Common/blob/dev/src/Microsoft.Framework.BufferEntryCollection.Sources/project.json

**Comment by Eilon** [comment]
@pranavkm does this matter anymore?

**Comment by pranavkm** [comment]
We should be good to close this. Most of our libraries point to `dotnet5.4` \ `netcore50` and don't have `DNX*` in them.

**Comment by Eilon** [comment]
Cool.
