### ISSUE TITLE
Multitarget to support .Net Standard 1

### ISSUE THREAD

**Issue by jrsearles** [aspnet/Common#295]
Would it be possible to update these libraries to multitarget .Net Standard 1.+? We are supporting a large codebase that cannot yet be updated to leverage 2.0 and would like to use pieces from this library. Specifically the efficient string manipulation supported in Microsoft.Extensions.Primitives.

**Comment by Eilon** [comment]
Hi @jrsearles to use .NET Standard 1.x you'll need to use ASP.NET Core 1.x and its related libraries. There are no plans to move anything else to support the previous versions. You can certainly take the code that's in this repo and compile it for other platforms/frameworks.
