### ISSUE TITLE
ObjectPool.Return could give back success status

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Common#296]
When we return an object, the object might not be returned in the queue. It would be useful to know about it by returning a bool. The caller could then decide to dispose any resource associated with this object as we can't reuse it.

**Comment by Eilon** [comment]
Wouldn't you always want to clean up the resources associated with the object? In your case, what are the "other resources"?

**Comment by pranavkm** [comment]
@Eilon things like DbConnection \ HttpClient where you might want to keep the instance around until the pool goes out of scope.

**Comment by Eilon** [comment]
Got it, chatted with @rynowak and @sebastienros in person. We'll hold onto it in the backlog to see if there's more demand for this.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2359
