### ISSUE TITLE
`PropertyHelper` does not provide information about inherited properties for interfaces

### ISSUE THREAD

**Issue by dougbu** [aspnet/Common#33]
Due to this problem, callers see fewer properties than expected e.g. `IList<T>` appears to have no properties (we ignore the indexer but that's expected) and MVC throws NREs whenever it attempts to use metadata for its `Count` property. The same thing would happen for a user's hierarchy of interfaces.

For example, including the following in a view
``` html
<h3>@Html.DisplayNameFor(m => m.Count)</h3>
<p>@Model.Count</p>
```
results in
```
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNet.Mvc.Rendering.HtmlHelper.GenerateDisplayName(ModelExplorer modelExplorer, String expression)
Microsoft.AspNet.Mvc.Rendering.HtmlHelper`1.DisplayNameFor[TResult](Expression`1 expression)
Asp.ASPV__Views_Home_About_cshtml.<ExecuteAsync>d__17.MoveNext() in About.cshtml
    <h3>@Html.DisplayNameFor(m => m.Count)</h3>
```

**Comment by dougbu** [comment]
Note that while the scenario seems unusual, it's easy to hit if you tend to use `<input disabled="disabled" ... />` elements to show information and the failure is extreme.

**Comment by Eilon** [comment]
Why would `<input disabled="disabled" ... />` have any effect on this?

**Comment by dougbu** [comment]
@Eilon sorry, was a bit abbreviated. Fuller example would be
``` html
  <input asp-for="Count" disabled="disabled" readonly="readonly" type="number"/>
```

**Comment by Eilon** [comment]
But what does this have to do with `<input>` tags at all, let alone being disabled?

**Comment by Eilon** [comment]
That is, wouldn't this happen with anything at all that uses expressions to target a property of an interface?

**Comment by dougbu** [comment]
Not all expressions. The difference is using an expression versus using a lambda expression where MVC needs its metadata. In particular
- `<p>@interface.InheritedProperty</p>` -- fine
- `<p>@Html.NameFor(m => interface.InheritedProperty)</p>` -- fine (just needs the expression name)
- `<p>@Html.DisplayNameFor(m => interface.InheritedProperty)</p>` -- hits #33
- `<input asp-for="Count" disabled="disabled" readonly="readonly" type="number"/>` -- hits #33

(And I used a `disabled` `<input/>` only because my example uses `Count` which has no setter. So a display-only field is more reasonable than another tag helper.)

**Comment by Eilon** [comment]
Of course not all expressions, but any case that uses an "affected expression" is of interest, regardless of where it's used.

**Comment by dougbu** [comment]
Yup. Sorry my example confused things.

**Comment by Eilon** [comment]
Thanks :smile: I just wanted to make sure I understood the scope of this.

**Comment by dougbu** [comment]
a1bb40e
