### ISSUE TITLE
BufferedHtmlContent must encode strings which are appended.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Common#34]
Currently the `string`s which are appended using `BufferedHtmlContent.Append(string)` are not encoded when written. We must encode them. https://github.com/aspnet/Common/pull/32#issuecomment-128893246

**Comment by dougbu** [comment]
Could we remove MVC's [`StringHtmlContent`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/StringHtmlContent.cs) when reacting to a fix for this issue in that repo?

**Comment by rynowak** [comment]
:+1:

**Comment by rynowak** [comment]
Poached!

**Comment by dougbu** [comment]
:+1:

**Comment by rynowak** [comment]
8376b8d8d895652fb6caf9a5a17f34d270542bc0
