### ISSUE TITLE
A dereferenced instance of MemoryPoolSlab may never be GC'ed / finalized 

### ISSUE THREAD

**Issue by baal2000** [aspnet/Common#391]
@pakrym 

May not be a real issue but reading [MemoryPoolSlab.IsActive](https://github.com/aspnet/Common/blob/da938fa2a1f5a6582f999c93cde7ab7795793eee/shared/Microsoft.Extensions.Buffers.MemoryPool.Sources/MemoryPoolSlab.cs#L36) comments:

> ... and (3) when all block tracking objects are garbage collected and the slab is no longer references the slab will be garbage collected and the memory unpinned will be unpinned by the slab's Dispose.

I look at the class [constructor](https://github.com/aspnet/Common/blob/da938fa2a1f5a6582f999c93cde7ab7795793eee/shared/Microsoft.Extensions.Buffers.MemoryPool.Sources/MemoryPoolSlab.cs#L24) and see the instance firmly GC-pinned. Nothing should be able to undo that except the explicit call to [Dispose()](https://github.com/aspnet/Common/blob/da938fa2a1f5a6582f999c93cde7ab7795793eee/shared/Microsoft.Extensions.Buffers.MemoryPool.Sources/MemoryPoolSlab.cs#L74).

I am missing something?

Thanks

**Comment by pakrym** [comment]
We call `GCHandle.Alloc` on `data` array not on `this`. MemoryPoolSlab instance would still get GCed

**Comment by baal2000** [comment]
@pakrym
My bad. Thanks!
