### ISSUE TITLE
Remove chaining from HashCodeCombiner

### ISSUE THREAD

**Issue by rynowak** [aspnet/Common#40]
Spot the bug:
```
public class TagBuilder
{
    private Dictionary<string, string> _attributes;
    private string _tagName;
    private string _innerContent;

    public override int GetHashCode()
    {
        var hash = HashCodeCombiner.Start()
            .Add(_tagName, StringComparer.Ordinal)
            .Add(_innerContent, StringComparer.Ordinal);

        foreach (var kvp in _attributes)
        {
            hash.Add(kvp.Key, StringComparer.Ordinal).Add(kvp.Value, StringComparer.Ordinal);
        }
    
        return hash.Build();
    }
}
```

It's too easy to get this wrong combining a builder and a mutable struct. We rarely have good unit tests for things like `GetHashCode()`. It's a better investment for us to remove chaining and write the extra 20 characters in each of these `GetHashCode()` methods than it is for us to write all the unit tests it would take to ensure correctness that way.

**Comment by dougbu** [comment]
Nice catch :+1:

**Comment by Eilon** [comment]
:+1: nice find.

**Comment by rynowak** [comment]
Don't thank me, thank @pranavkm
