### ISSUE TITLE
*.Sources packages should not have assemblies in them

### ISSUE THREAD

**Issue by muratg** [aspnet/Common#41]
These are Source only assemblies.  The packages currently contain assemblies inside `lib` folder.

**Comment by Eilon** [comment]
@muratg is this a fix we need in Common, or is it a bug in how DNX does source-only packages?

@davidfowl ?

**Comment by muratg** [comment]
I'm under the impression that each *.Sources project will need to be fixed, but I may be wrong.

@NTaylorMullen may have some input on this one.

**Comment by davidfowl** [comment]
It's DNX

**Comment by Eilon** [comment]
@muratg move to DNX then?

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/2720 :smile:

**Comment by Eilon** [comment]
Ok then :smile:

**Comment by NTaylorMullen** [comment]
:+1:
