### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/Common#46]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by pranavkm** [comment]
https://github.com/aspnet/Common/commit/ec2fdbcf1fb79c7c14a9a47a1cf48e2426d40a25
