### ISSUE TITLE
Need to add missing doc comments in some projects

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Common#82]
For XML files to be generated as part of the build, dotnet needs "xmlDoc": true to be added to project.json. For this to be done we first need to fix all the warnings(which show as errors) about missing XML doc comments. There are a bunch of those errors in the following projects.
1. Microsoft.Extensions.CommandLineUtils
2. Microsoft.Extensions.ObjectPool
3. Microsoft.Extensions.Primitives

@muratg @victorhurdugaci

**Comment by victorhurdugaci** [comment]
cc @BrennanConroy for CommandLineUtils

**Comment by muratg** [comment]
@ajaybhargavb just synced up with Eilon.  For now, we can add a "dummy" comment in a class for these repos to prevent the warnings.

**Comment by Eilon** [comment]
Actually what we're going to do is generate the docs for all the projects, but disable the particular warning about missing docs. See this bug: https://github.com/dotnet/cli/issues/576

**Comment by ajaybhargavb** [comment]
This is currently blocked because of this issue https://github.com/dotnet/roslyn/issues/8750.

**Comment by victorhurdugaci** [comment]
Can we just change the aliases ('object') to be the actual type ('Object') to get you unblocked?

**Comment by ajaybhargavb** [comment]
I thought about doing that but that doesn't work in this (https://github.com/dotnet/roslyn/issues/8750#issuecomment-184932785) case .

**Comment by ajaybhargavb** [comment]
All repos have been updated.
