### ISSUE TITLE
CommandLineUtils help is always listed as the second item

### ISSUE THREAD

**Issue by muratg** [aspnet/Common#89]
_From @dotnetshadow on January 29, 2016 3:37_

Hi I noticed that the help command appears second in the list of commands irrespective of the order of commands: This is as of version asp.net 5 rc1

```
   var app = new CommandLineApplication
            {
                Name = "dnx mytest",
                FullName = "MyTest Commands"
            };
            app.VersionOption("--version", PlatformServices.Default.Application.ApplicationVersion);
            app.HelpOption("-?|-h|--help");

            app.OnExecute(() =>
                {
                    //ShowLogo();
                    app.ShowHelp();

                    return 0;
                });

            app.Command(
               "command1",
               database =>
               {                   
                   
               });

            app.Command(
              "command2",
              database =>
              {

              });
            return app.Execute(args);
```

![image](https://cloud.githubusercontent.com/assets/296247/12666505/a03a3e94-c695-11e5-90c8-576054b5e162.png)

_Copied from original issue: aspnet/dnx#3343_

**Comment by dotnetshadow** [comment]
What happened to this issue? Wwhy is it closed?

**Comment by ryanbrandenburg** [comment]
Is there some other repro step to this? when I drop that code into a console app and run it help doesn't list in the command list at all. @dotnetshadow does this still repro for you with the latest?

**Comment by dotnetshadow** [comment]
I noticed with the updated rc2 stuff the help command doesn't display and instead it's just an option, If I use the RC1 bits then the problem exists. Perhaps you are using a newer version?

**Comment by ryanbrandenburg** [comment]
Yes, I was using RC2, but for a bug of this severity we won't hotfix RC1. So since it seems we're already fixed in RC2 I'll close this one.
