### ISSUE TITLE
Remove duplicated `WebEncoders` class

### ISSUE THREAD

**Issue by dougbu** [aspnet/Common#93]
A big chunk of `Microsoft.AspNetCore.WebUtilities.WebEncoders` (for base64url-encoding and -decoding) is duplicated in `Microsoft.AspNetCore.DataProtection.WebEncoders`. With aspnet/HttpAbstractions#563, these classes are getting less aligned and DataProtection can't take advantage of the expanded API.

After a few offline discussions, have two ways to remove this wart:

1. Move `WebEncoders` from HttpAbstractions to Common
 - `#if` the code such that it is placed in `Microsoft.AspNetCore.DataProtection.Internal` or `Microsoft.AspNetCore.WebUtilities`, depending on a flag.
    - In the DataProtection version, could make the class `internal` and leave it in `Microsoft.AspNetCore.DataProtection` if anyone feels strongly.
 - Use the new Common version in both DataProtection and HttpAbstractions (where it remains publicly exposed).
 - Leave Antiforgery and MVC alone; they will continue to rely on the `public` class in HttpAbstractions.
2. Reuse the approach we took for `ActivatorUtilities` and place `WebEncoders` as an `internal` class in `Microsoft.Extensions.Internal` then expose it through a facade in HttpAbstractions. That avoids the oddity of a `public` class in a `Blah.Blah.Blah.Sources` package and makes the moved class more consistent w/ others in Common. But it involves more ceremony.

**Comment by Eilon** [comment]
I believe we discussed doing option (1), right?

**Comment by dougbu** [comment]
>  believe we discussed doing option (1), right?

Yup, Then I went back and saw going that way was unlike the other .Sources code in Common. So I wanted to triple-check and see if anyone else wanted to weigh in.

**Comment by Eilon** [comment]
I think it's the only option that makes sense, so I don't think there's any other reasonable way to go, no? We don't want a façade, and we don't want a public class for this...

**Comment by dougbu** [comment]
Suggest this is cleanup we can postpone 'til 1.0.1. We aren't planning to make a change in what's publicly exposed here.

**Comment by Eilon** [comment]
Moved.

**Comment by dougbu** [comment]
- fe2bf2c
- aspnet/DataProtection@4f30ddd
- aspnet/HttpAbstractions@9a28932
